name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version:
        - '10.0.0'
        - '15.2.0'

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run clean
    - run: npm run lint
    - run: npm run build
